language: bash
services: docker

env:
  global:
    - secure:
    - GITHUB_REPO_NAME=docker-liferay-portal-ce
  matrix:
    - VERSION=7.1.3-ga4 VARIANT=jdk8-slim

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="$DOCKER_USERNAME/liferay-portal-ce:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" ./"$VERSION/$VARIANT"
      ~/official-images/test/run.sh "$image"
      docker push "$image"
      ./readme/generate-readme.sh "$VERSION/$VARIANT" "$TRAVIS_COMMIT"
      git status
    )

after_success:
  - docker images
  - ./push-remote.sh
