language: bash
services: docker

env:
  global:
    - secure:
  matrix:
    - VERSION=7.1.3-ga4 VARIANT=jdk8-alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="$DOCKER_USERNAME/liferay-portal-ce:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" ./"$VERSION/$VARIANT"
      ~/official-images/test/run.sh "$image"
    )

after_success:
  - docker images
